name: Daily Commit

on:
  schedule:
    - cron: '0 0 * * *'  # Har din midnight (UTC time) par run hoga

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Update README with current date
      run: |
        echo -e "\n## Last Updated: $(date +'%Y-%m-%d %H:%M:%S')" >> README.md

    - name: Make a daily commit
      run: |
        git config --global user.name "hamzahashmi3"
        git config --global user.email "technocannons3@gmail.com"
        git add README.md
        git commit -m "Daily commit: Updated README with current date"
        git push